version: '2'
services:
  vue:
    build: .
    ports:
      - "8080:8080"
    environment:
      - YARN_CACHE_FOLDER=/cache
    volumes:
      - .:/app
      - ./cache/yarn:/cache
    environment:
      - NODE_ENV=development
      - PORT=8080
      - HOST=0.0.0.0
    working_dir: /app
